//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIT_Campus_Housing_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentRecord()
        {
            this.LoginDetails = new HashSet<LoginDetail>();
        }
    
        public int StudentID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string NationalID { get; set; }
        public string RegNumber { get; set; }
        public string Part { get; set; }
        public string School { get; set; }
        public string Course { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string HITmail { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginDetail> LoginDetails { get; set; }
    }
}
