//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIT_Campus_Housing_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptID { get; set; }
        public string Schools { get; set; }
        public string SIETdepartment { get; set; }
        public string SISTdepartment { get; set; }
        public string SAHSdepartment { get; set; }
        public string SBMSdepartment { get; set; }
        public string SIITdepartment { get; set; }
        public string Part { get; set; }
    }
}
